name: adaptor-firebase-auth

services:
  app:
    container_name: adaptor-firebase-auth
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile.dev
    volumes:
      - ./:/src/go
    ports:
      - 8080:8080
    working_dir: /src/go
    command: air -c .air.toml
    depends_on:
      - mysql
      - redis
      - wiremock
    networks:
      - app-network

networks:
  app-network:
    external: true
